<?php

namespace AppBundle\Repository;

/**
 * ropaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ropaRepository extends \Doctrine\ORM\EntityRepository
{
}
